### PR TITLE
complete ticket list

### LINKED ISSUE #18: Ticket list page
Following components are required:
- Data Table
- Pagination
- Filter
- Action buttons (Create, Edit and Delete)

### PR DESCRIPTION
**Pull request by gitfullstacker**
CURD design

### CODE REVIEW

**Comment by gitfullstacker** [comment]
@johnsmith0305 I finished designing the basic CRUD functionality.
I'm uncertain about what additional functionalities are needed.

**Review by johnsmith0305 — CHANGES_REQUESTED** [review]
This is perfect.
I think we need the filter functionality in main table.

**Comment by gitfullstacker** [comment]
> This is perfect. I think we need the filter functionality in main table.

Okay, I'll incorporate some filter inputs at the top of the table, sound good?

**Comment by gitfullstacker** [comment]
image
I will use this

**Comment by johnsmith0305** [comment]
> image I will use this

I agree

**Comment by gitfullstacker** [comment]
I incorporated the filter functionality.

**Review by johnsmith0305 — APPROVED** [review]
Excellent!!!

**Pull request merged**
